name: Count Files and Update README

on:
  push:
    branches:
      - main  # Adjust to your default branch
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  count-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make script executable
        run: chmod +x count_files.sh

      - name: Run file counting script
        run: ./count_files.sh

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update file counts in README" || echo "No changes to commit"
          git push